### ISSUE TITLE
captchagen is no longer working with new canvas version

### ISSUE THREAD

**Issue by smithb1994** [contra/captchagen#19]
Captchagen is no longer working with new canvas version.
I suggest setting package.json canvas version to ^1.6.9.

**Comment by contra** [comment]
@smithb1994 Want to send a PR?

**Comment by smithb1994** [comment]
See #20

**Comment by contra** [comment]
Had issues installing so I'm actually going to upgrade this to work w/ latest canvas.

**Comment by yocontra** [comment]
Published as 1.2.0
